### ISSUE TITLE
Lack of examples of how to use it for use with http in the standard library

### ISSUE THREAD

**Issue by pwaller** [rcrowley/goagain#20]
I like the idea of goagain, but I'm surprised that so much code has to live in my `main()`. Can't we have a `goagain.HttpListenAndserve()`? This would be much more user friendly and solve the common case that one just wants to use go's builtin http server.

Is there a good reason it is not like this?

**Comment by josephholsten** [comment]
Sounds like you basically want to merge [manners](https://github.com/braintree/manners) into goagain. Which I entirely support.

**Comment by pwaller** [comment]
:+1:. I'll attempt to whip something up and pull request it.

**Comment by rcrowley** [comment]
An example to that effect would be great!  I haven't seen manners before but have implemented that pattern and that's as close as you can get to a proper graceful stop without hacking net/http to add a fast return path between requests for a server that should be stopping.

**Comment by pwaller** [comment]
It's unfortunate that I gracefully-stopping http server isn't in the standard library. One problem with manners is that it uses global state so you can only have one server.

**Comment by mattbaird** [comment]
hi @pwaller are you still planning on doing this? I have the same need and was going to start working on it as well if you haven't made progress.

**Comment by pwaller** [comment]
@mattbaird manners has since improved to not use global state, and I solved my problem in a different way in the end by doing the `exec` myself. I'd still like to see `goagain` improved though, but I'm not likely to work on it just now.

**Comment by titanous** [comment]
[mannersagain](https://github.com/cupcake/mannersagain) combines the two into a drop-in replacement for `http.ListenAndServe`.

**Comment by rcrowley** [comment]
Nice!  Go 1.3 is going to open up everything we need to do graceful stop and zero-downtime restarts correctly and after that's live I'll get things documented and wired up.

**Comment by pwaller** [comment]
@rcrowley, could you link or quote what you're referring to? You've got me all curious.

**Comment by sgirones** [comment]
Looking forward to it! I wonder how does people manage this in production...

**Comment by rcrowley** [comment]
Standard library improvements:
- http://tip.golang.org/pkg/net/http/#ConnState
- http://tip.golang.org/pkg/net/http/#Server.SetKeepAlivesEnabled

Use in Tiger Tonic to enable graceful stop:
- https://github.com/rcrowley/go-tigertonic/compare/go1.3

**Comment by pwaller** [comment]
Nice, thanks.
