### ISSUE TITLE
Leaks file descriptors on graceful reload

### ISSUE THREAD

**Issue by ManuelAmadorAditazz** [rcrowley/goagain#5]
The first time it runs.

goagain-e 9114     manuel    0u      CHR              136,0      0t0         3 /dev/pts/0
goagain-e 9114     manuel    1u      CHR              136,0      0t0         3 /dev/pts/0
goagain-e 9114     manuel    2u      CHR              136,0      0t0         3 /dev/pts/0
goagain-e 9114     manuel    3u     IPv4             678836      0t0       TCP 127.0.0.1:48879 (LISTEN)
goagain-e 9114     manuel    4r     FIFO                0,8      0t0    678837 pipe
goagain-e 9114     manuel    5w     FIFO                0,8      0t0    678837 pipe
goagain-e 9114     manuel    6u     0000                0,9        0      6869 anon_inode
goagain-e 9114     manuel   17r      REG                0,3        0    410676 /proc/4972/auxv

Every subsequent time, it adds two more sockets.

goagain-e 9268     manuel    0u      CHR              136,0      0t0         3 /dev/pts/0
goagain-e 9268     manuel    1u      CHR              136,0      0t0         3 /dev/pts/0
goagain-e 9268     manuel    2u      CHR              136,0      0t0         3 /dev/pts/0
goagain-e 9268     manuel    3u     IPv4             678836      0t0       TCP 127.0.0.1:48879 (LISTEN)
goagain-e 9268     manuel    4u     IPv4             678836      0t0       TCP 127.0.0.1:48879 (LISTEN)
goagain-e 9268     manuel    5r     FIFO                0,8      0t0    688469 pipe
goagain-e 9268     manuel    6w     FIFO                0,8      0t0    688469 pipe
goagain-e 9268     manuel    7u     IPv4             678836      0t0       TCP 127.0.0.1:48879 (LISTEN)
goagain-e 9268     manuel    8u     0000                0,9        0      6869 anon_inode
goagain-e 9268     manuel   17r      REG                0,3        0    410676 /proc/4972/auxv

Where are you reopening the socket?

Runtime go is the one that ships with Ubuntu 12.04.

**Comment by ManuelAmadorAditazz** [comment]
Upgradable.go also has the same issue, but they only leak one socket: http://code.google.com/p/jra-go/issues/detail?id=1&thanks=1&ts=1363993927

**Comment by ManuelAmadorAditazz** [comment]
"if you pass the file with cmd.ExtraFiles, then the FD will always be 3"  <- sounds promising

**Comment by ManuelAmadorAditazz** [comment]
Here is an example: https://code.google.com/p/go/source/browse/src/pkg/syscall/passfd_test.go

**Comment by rcrowley** [comment]
@ManuelAmadorAditazz The `passfd_test.go` example implements the same pattern as Node.js's cluster module.  Thanks for the link.

**Comment by rcrowley** [comment]
Fixed by 20cd4074652a353491f9851cc9d16fe07fb87b5e and `syscall.Close` in 743bb5640451a3b3736d81e6502fae3175ef816c.
