### ISSUE TITLE
Doesn't finish ongoing requests on reload

### ISSUE THREAD

**Issue by ManuelAmadorAditazz** [rcrowley/goagain#6]
Unlike http://code.google.com/p/jra-go/source/browse/cmd/upgradable/main.go, the parent process doesn't actually stop listening or wait until it's done handling all requests, before it dies.  This is because the child kills the parent and the parent exits unconditionally.  This causes loss of requests.

**Comment by ManuelAmadorAditazz** [comment]
We have made significant progress with goagain, significant enough that I can say:
- We will be done adding UNIX socket support to it very soon.
- We have made the program linger after being signaled and forking its child, processing any slow ongoing requests, but not accepting new ones (in turn, delegating the accept of new connections to the child) 
- We have eliminated the issue whereby the child would kill the parent, aborting ongoing requests

We hope to submit code upstream soon.

**Comment by rcrowley** [comment]
This is great, @ManuelAmadorAditazz!  I've been of the opinion that the caller of `goagain.AwaitSignals` had the opportunity to do his cleanup after that call returns but a default strategy of "just give it time" would cover the common case well.

**Comment by ManuelAmadorAditazz** [comment]
I am glad that you like the code that I wrote. If you would consider
merging it what would I have to do to clean it up?

Also how do we support both Unix and TCP sockets?
