### ISSUE TITLE
Support UNIX domain sockets in addition to TCP sockets

### ISSUE THREAD

**Issue by rcrowley** [rcrowley/goagain#8]
This came up in #6 and #7 so I'd like to oblige.

**Comment by rcrowley** [comment]
@ManuelAmadorAditazz @Rudd-O Does this patch address your needs as far as UNIX domain sockets are concerned?

**Comment by ManuelAmadorAditazz** [comment]
Here you go:

https://github.com/Rudd-O/goagain

(unix and TCP socket support)

:-)

**Comment by ManuelAmadorAditazz** [comment]
Your last commit doesn't actually make the program listen on unix domain sockets.  My fork supports that.
